package enumerations;

public enum MessageContent {
    CONNECTION, CONNECTION_RESPONSE, GET_IN_LOBBY, COLOR, COLOR_RESPONSE, GAME_SETUP,
    BOT_SPAWN, DISCARD_POWERUP, BOT_ACTION, MOVE, MOVE_PICK, SHOOT, RELOAD, POWERUP_USAGE,
    PASS_TURN, RESPONSE, GAME_STATE, WINNER, DISCONNECTION, PING, READY, RECONNECTION
}
