package enumerations;

public enum MessageContent {
    CONNECTION, READY, GAME_SETUP, TERMINATOR_SPAWN, DISCARD_POWERUP,
    TERMINATOR, MOVE, MOVE_PICK, SHOOT, RELOAD, POWERUP, PASS_TURN,
    RESPONSE, GAME_STATE, LAST_RESPONSE
}
