package enumerations;

public enum PossibleGameState {
    GAME_ROOM, GAME_READY, GAME_STARTED, FINAL_FRENZY, SECOND_ACTION,
    MISSING_TERMINATOR_ACTION, TERMINATOR_USED, GRANADE_USAGE, SCOPE_USAGE,
    PASS_NORMAL_TURN, PASS_FRENZY_TURN, ACTIONS_DONE, FRENZY_ACTIONS_DONE,
    MANAGE_DEATHS, TERMINATOR_RESPAWN
}
