package enumerations;

public enum PossibleGameState {
    GAME_ROOM, GAME_READY, GAME_STARTED, FINAL_FRENZY, SECOND_ACTION,
    MISSING_TERMINATOR_ACTION, TERMINATOR_USED, GRANADE_USAGE, MANAGE_DEATHS,
    PASS_TURN, ACTIONS_DONE, FRENZY_ACTIONS_DONE, ENDGAME
}
