package enumerations;

public enum UserPlayerState {
    BOT_SPAWN,
    SPAWN,
    FIRST_ACTION,
    SECOND_ACTION,
    FIRST_FRENZY_ACTION,
    SECOND_FRENZY_ACTION,
    ENDING_PHASE,
    END,
    DEAD,
    BOT_RESPAWN,
    BOT_ACTION,
    GRENADE_USAGE,
    FIRST_SCOPE_USAGE,
    SECOND_SCOPE_USAGE
}
