package enumerations;

public enum UserPlayerState {
    SPAWN, BEGIN, FIRST_ACTION, SECOND_ACTION, BOT_FIRST,
    BOT_SECOND, BOT_THIRD, END, BOT_ACTION,
    RELOAD, FIRST_FRENZY_ACTION, SECOND_FRENZY_ACTION
}
